MoveTable:
	dw Move_POUND
	dw Move_KARATE_CHOP
	dw Move_DOUBLESLAP
	dw Move_COMET_PUNCH
	dw Move_MEGA_PUNCH
	dw Move_PAY_DAY
	dw Move_FIRE_PUNCH
	dw Move_ICE_PUNCH
	dw Move_THUNDERPUNCH
	dw Move_SCRATCH
	dw Move_VICEGRIP
	dw Move_GUILLOTINE
	dw Move_RAZOR_WIND
	dw Move_SWORDS_DANCE
	dw Move_CUT
	dw Move_GUST
	dw Move_WING_ATTACK
	dw Move_WHIRLWIND
	dw Move_FLY
	dw Move_BIND
	dw Move_SLAM
	dw Move_VINE_WHIP
	dw Move_STOMP
	dw Move_DOUBLE_KICK
	dw Move_MEGA_KICK
	dw Move_JUMP_KICK
	dw Move_ROLLING_KICK
	dw Move_SAND_ATTACK
	dw Move_HEADBUTT
	dw Move_HORN_ATTACK
	dw Move_FURY_ATTACK
	dw Move_HORN_DRILL
	dw Move_TACKLE
	dw Move_BODY_SLAM
	dw Move_WRAP
	dw Move_TAKE_DOWN
	dw Move_THRASH
	dw Move_DOUBLE_EDGE
	dw Move_TAIL_WHIP
	dw Move_POISON_STING
	dw Move_TWINEEDLE
	dw Move_PIN_MISSILE
	dw Move_LEER
	dw Move_BITE
	dw Move_GROWL
	dw Move_ROAR
	dw Move_SING
	dw Move_SUPERSONIC
	dw Move_SONICBOOM
	dw Move_DISABLE
	dw Move_ACID
	dw Move_EMBER
	dw Move_FLAMETHROWER
	dw Move_MIST
	dw Move_WATER_GUN
	dw Move_HYDRO_PUMP
	dw Move_SURF
	dw Move_ICE_BEAM
	dw Move_BLIZZARD
	dw Move_PSYBEAM
	dw Move_BUBBLEBEAM
	dw Move_AURORA_BEAM
	dw Move_HYPER_BEAM
	dw Move_PECK
	dw Move_DRILL_PECK
	dw Move_SUBMISSION
	dw Move_LOW_KICK
	dw Move_COUNTER
	dw Move_SEISMIC_TOSS
	dw Move_STRENGTH
	dw Move_ABSORB
	dw Move_MEGA_DRAIN
	dw Move_LEECH_SEED
	dw Move_GROWTH
	dw Move_RAZOR_LEAF
	dw Move_SOLARBEAM
	dw Move_POISONPOWDER
	dw Move_STUN_SPORE
	dw Move_SLEEP_POWDER
	dw Move_PETAL_DANCE
	dw Move_STRING_SHOT
	dw Move_DRAGON_RAGE
	dw Move_FIRE_SPIN
	dw Move_THUNDERSHOCK
	dw Move_THUNDERBOLT
	dw Move_THUNDER_WAVE
	dw Move_THUNDER
	dw Move_ROCK_THROW
	dw Move_EARTHQUAKE
	dw Move_FISSURE
	dw Move_DIG
	dw Move_TOXIC
	dw Move_CONFUSION
	dw Move_PSYCHIC_M
	dw Move_HYPNOSIS
	dw Move_MEDITATE
	dw Move_AGILITY
	dw Move_QUICK_ATTACK
	dw Move_RAGE
	dw Move_TELEPORT
	dw Move_NIGHT_SHADE
	dw Move_MIMIC
	dw Move_SCREECH
	dw Move_DOUBLE_TEAM
	dw Move_RECOVER
	dw Move_HARDEN
	dw Move_MINIMIZE
	dw Move_SMOKESCREEN
	dw Move_CONFUSE_RAY
	dw Move_WITHDRAW
	dw Move_DEFENSE_CURL
	dw Move_BARRIER
	dw Move_LIGHT_SCREEN
	dw Move_HAZE
	dw Move_REFLECT
	dw Move_FOCUS_ENERGY
	dw Move_BIDE
	dw Move_METRONOME
	dw Move_MIRROR_MOVE
	dw Move_SELFDESTRUCT
	dw Move_EGG_BOMB
	dw Move_LICK
	dw Move_SMOG
	dw Move_SLUDGE
	dw Move_BONE_CLUB
	dw Move_FIRE_BLAST
	dw Move_WATERFALL
	dw Move_CLAMP
	dw Move_SWIFT
	dw Move_SKULL_BASH
	dw Move_SPIKE_CANNON
	dw Move_CONSTRICT
	dw Move_AMNESIA
	dw Move_KINESIS
	dw Move_SOFTBOILED
	dw Move_HI_JUMP_KICK
	dw Move_GLARE
	dw Move_DREAM_EATER
	dw Move_POISON_GAS
	dw Move_BARRAGE
	dw Move_LEECH_LIFE
	dw Move_LOVELY_KISS
	dw Move_SKY_ATTACK
	dw Move_TRANSFORM
	dw Move_BUBBLE
	dw Move_DIZZY_PUNCH
	dw Move_SPORE
	dw Move_FLASH
	dw Move_PSYWAVE
	dw Move_SPLASH
	dw Move_ACID_ARMOR
	dw Move_CRABHAMMER
	dw Move_EXPLOSION
	dw Move_FURY_SWIPES
	dw Move_BONEMERANG
	dw Move_REST
	dw Move_ROCK_SLIDE
	dw Move_HYPER_FANG
	dw Move_SHARPEN
	dw Move_CONVERSION
	dw Move_TRI_ATTACK
	dw Move_SUPER_FANG
	dw Move_SLASH
	dw Move_SUBSTITUTE
	dw Move_STRUGGLE

Move:
.POUND
	db "POUND",$FF
.KARATE_CHOP
	db "KARATE CHOP",$FF
.DOUBLESLAP
	db "DOUBLESLAP",$FF
.COMET_PUNCH
	db "COMET PUNCH",$FF
.MEGA_PUNCH
	db "MEGA PUNCH",$FF
.PAY_DAY
	db "PAY DAY",$FF
.FIRE_PUNCH
	db "FIRE PUNCH",$FF
.ICE_PUNCH
	db "ICE PUNCH",$FF
.THUNDERPUNCH
	db "THUNDER PUNCH",$FF
.SCRATCH
	db "SCRATCH",$FF
.VICEGRIP
	db "VICEGRIP",$FF
.GUILLOTINE
	db "GUILLOTINE",$FF
.RAZOR_WIND
	db "RAZOR WIND",$FF
.SWORDS_DANCE
	db "SWORDS DANCE",$FF
.CUT
	db "CUT",$FF
.GUST
	db "GUST",$FF
.WING_ATTACK
	db "WING ATTACK",$FF
.WHIRLWIND
	db "WHIRLWIND",$FF
.FLY
	db "FLY",$FF
.BIND
	db "BIND",$FF
.SLAM
	db "SLAM",$FF
.VINE_WHIP
	db "VINE WHIP",$FF
.STOMP
	db "STOMP",$FF
.DOUBLE_KICK
	db "DOUBLE KICK",$FF
.MEGA_KICK
	db "MEGA KICK",$FF
.JUMP_KICK
	db "JUMP KICK",$FF
.ROLLING_KICK
	db "ROLLING KICK",$FF
.SAND_ATTACK
	db "SAND ATTACK",$FF
.HEADBUTT
	db "HEADBUTT",$FF
.HORN_ATTACK
	db "HORN ATTACK",$FF
.FURY_ATTACK
	db "FURY ATTACK",$FF
.HORN_DRILL
	db "HORN DRILL",$FF
.TACKLE
	db "TACKLE",$FF
.BODY_SLAM
	db "BODY SLAM",$FF
.WRAP
	db "WRAP",$FF
.TAKE_DOWN
	db "TAKE DOWN",$FF
.THRASH
	db "THRASH",$FF
.DOUBLE_EDGE
	db "DOUBLE EDGE",$FF
.TAIL_WHIP
	db "TAIL WHIP",$FF
.POISON_STING
	db "POISON STING",$FF
.TWINEEDLE
	db "TWINEEDLE",$FF
.PIN_MISSILE
	db "PIN MISSILE",$FF
.LEER
	db "LEER",$FF
.BITE
	db "BITE",$FF
.GROWL
	db "GROWL",$FF
.ROAR
	db "ROAR",$FF
.SING
	db "SING",$FF
.SUPERSONIC
	db "SUPERSONIC",$FF
.SONICBOOM
	db "SONICBOOM",$FF
.DISABLE
	db "DISABLE",$FF
.ACID
	db "ACID",$FF
.EMBER
	db "EMBER",$FF
.FLAMETHROWER
	db "FLAMETHROWER",$FF
.MIST
	db "MIST",$FF
.WATER_GUN
	db "WATER GUN",$FF
.HYDRO_PUMP
	db "HYDRO PUMP",$FF
.SURF
	db "SURF",$FF
.ICE_BEAM
	db "ICE BEAM",$FF
.BLIZZARD
	db "BLIZZARD",$FF
.PSYBEAM
	db "PSYBEAM",$FF
.BUBBLEBEAM
	db "BUBBLEBEAM",$FF
.AURORA_BEAM
	db "AURORA BEAM",$FF
.HYPER_BEAM
	db "HYPER BEAM",$FF
.PECK
	db "PECK",$FF
.DRILL_PECK
	db "DRILL PECK",$FF
.SUBMISSION
	db "SUBMISSION",$FF
.LOW_KICK
	db "LOW KICK",$FF
.COUNTER
	db "COUNTER",$FF
.SEISMIC_TOSS
	db "SEISMIC TOSS",$FF
.STRENGTH
	db "STRENGTH",$FF
.ABSORB
	db "ABSORB",$FF
.MEGA_DRAIN
	db "MEGA DRAIN",$FF
.LEECH_SEED
	db "LEECH SEED",$FF
.GROWTH
	db "GROWTH",$FF
.RAZOR_LEAF
	db "RAZOR LEAF",$FF
.SOLARBEAM
	db "SOLARBEAM",$FF
.POISONPOWDER
	db "POISONPOWDER",$FF
.STUN_SPORE
	db "STUN SPORE",$FF
.SLEEP_POWDER
	db "SLEEP POWDER",$FF
.PETAL_DANCE
	db "PETAL DANCE",$FF
.STRING_SHOT
	db "STRING SHOT",$FF
.DRAGON_RAGE
	db "DRAGON RAGE",$FF
.FIRE_SPIN
	db "FIRE SPIN",$FF
.THUNDERSHOCK
	db "THUNDERSHOCK",$FF
.THUNDERBOLT
	db "THUNDERBOLT",$FF
.THUNDER_WAVE
	db "THUNDER WAVE",$FF
.THUNDER
	db "THUNDER",$FF
.ROCK_THROW
	db "ROCK THROW",$FF
.EARTHQUAKE
	db "EARTHQUAKE",$FF
.FISSURE
	db "FISSURE",$FF
.DIG
	db "DIG",$FF
.TOXIC
	db "TOXIC",$FF
.CONFUSION
	db "CONFUSION",$FF
.PSYCHIC_M
	db "PSYCHIC",$FF
.HYPNOSIS
	db "HYPNOSIS",$FF
.MEDITATE
	db "MEDITATE",$FF
.AGILITY
	db "AGILITY",$FF
.QUICK_ATTACK
	db "QUICK ATTACK",$FF
.RAGE
	db "RAGE",$FF
.TELEPORT
	db "TELEPORT",$FF
.NIGHT_SHADE
	db "NIGHT SHADE",$FF
.MIMIC
	db "MIMIC",$FF
.SCREECH
	db "SCREECH",$FF
.DOUBLE_TEAM
	db "DOUBLE TEAM",$FF
.RECOVER
	db "RECOVER",$FF
.HARDEN
	db "HARDEN",$FF
.MINIMIZE
	db "MINIMIZE",$FF
.SMOKESCREEN
	db "SMOKESCREEN",$FF
.CONFUSE_RAY
	db "CONFUSE RAY",$FF
.WITHDRAW
	db "WITHDRAW",$FF
.DEFENSE_CURL
	db "DEFENSE CURL",$FF
.BARRIER
	db "BARRIER",$FF
.LIGHT_SCREEN
	db "LIGHT SCREEN",$FF
.HAZE
	db "HAZE",$FF
.REFLECT
	db "REFLECT",$FF
.FOCUS_ENERGY
	db "FOCUS ENERGY",$FF
.BIDE
	db "BIDE",$FF
.METRONOME
	db "METRONOME",$FF
.MIRROR_MOVE
	db "MIRROR MOVE",$FF
.SELFDESTRUCT
	db "SELFDESTRUCT",$FF
.EGG_BOMB
	db "EGG BOMB",$FF
.LICK
	db "LICK",$FF
.SMOG
	db "SMOG",$FF
.SLUDGE
	db "SLUDGE",$FF
.BONE_CLUB
	db "BONE CLUB",$FF
.FIRE_BLAST
	db "FIRE BLAST",$FF
.WATERFALL
	db "WATERFALL",$FF
.CLAMP
	db "CLAMP",$FF
.SWIFT
	db "SWIFT",$FF
.SKULL_BASH
	db "SKULL BASH",$FF
.SPIKE_CANNON
	db "SPIKE CANNON",$FF
.CONSTRICT
	db "CONSTRICT",$FF
.AMNESIA
	db "AMNESIA",$FF
.KINESIS
	db "KINESIS",$FF
.SOFTBOILED
	db "SOFTBOILED",$FF
.HI_JUMP_KICK
	db "HI JUMP KICK",$FF
.GLARE
	db "GLARE",$FF
.DREAM_EATER
	db "DREAM EATER",$FF
.POISON_GAS
	db "POISON GAS",$FF
.BARRAGE
	db "BARRAGE",$FF
.LEECH_LIFE
	db "LEECH LIFE",$FF
.LOVELY_KISS
	db "LOVELY KISS",$FF
.SKY_ATTACK
	db "SKY ATTACK",$FF
.TRANSFORM
	db "TRANSFORM",$FF
.BUBBLE
	db "BUBBLE",$FF
.DIZZY_PUNCH
	db "DIZZY PUNCH",$FF
.SPORE
	db "SPORE",$FF
.FLASH
	db "FLASH",$FF
.PSYWAVE
	db "PSYWAVE",$FF
.SPLASH
	db "SPLASH",$FF
.ACID_ARMOR
	db "ACID ARMOR",$FF
.CRABHAMMER
	db "CRABHAMMER",$FF
.EXPLOSION
	db "EXPLOSION",$FF
.FURY_SWIPES
	db "FURY SWIPES",$FF
.BONEMERANG
	db "BONEMERANG",$FF
.REST
	db "REST",$FF
.ROCK_SLIDE
	db "ROCK SLIDE",$FF
.HYPER_FANG
	db "HYPER FANG",$FF
.SHARPEN
	db "SHARPEN",$FF
.CONVERSION
	db "CONVERSION",$FF
.TRI_ATTACK
	db "TRI ATTACK",$FF
.SUPER_FANG
	db "SUPER FANG",$FF
.SLASH
	db "SLASH",$FF
.SUBSTITUTE
	db "SUBSTITUTE",$FF
.STRUGGLE
	db "STRUGGLE",$FF
	