PokeNamesTable:
	dw Poke_BULBASAUR
	dw Poke_IVYSAUR
	dw Poke_VENUSAUR
	dw Poke_CHARMANDER
	dw Poke_CHARMELEON
	dw Poke_CHARIZARD
	dw Poke_SQUIRTLE
	dw Poke_WARTORTLE
	dw Poke_BLASTOISE
	
Poke:
.BULBASAUR
	db "BULBASAUR",$FF
.IVYSAUR
	db "IVYSAUR",$FF
.VENUSAUR
	db "VENUSAUR",$FF
.CHARMANDER
	db "CHARMANDER",$FF
.CHARMELEON
	db "CHARMELEON",$FF
.CHARIZARD
	db "CHARIZARD",$FF
.SQUIRTLE
	db "SQUIRTLE",$FF
.WARTORTLE
	db "WARTORTLE",$FF
.BLASTOISE
	db "BLASTOISE",$FF
	